name: zeus_extension
description: A complete cognitive extension for the ZEUS OS.
version: 1.0.6+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  http: ^1.2.0
  web_socket_channel: ^3.0.3
  flutter_tts: ^3.8.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  google_fonts: ^6.1.0
  audioplayers: ^6.0.0
  window_manager: ^0.4.3
  flutter_acrylic: ^1.1.4
  hotkey_manager: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # Adicione fontes futuristas aqui se necessário
